export const indices = [
  {
    id: "sp500",
    name: "S&P 500",
    symbol: "^GSPC",
    region: "USA",
    timezone: "America/New_York",
    closeHour: 16,
    closeMinute: 0,
  },
  {
    id: "nasdaq100",
    name: "Nasdaq-100",
    symbol: "^NDX",
    region: "USA",
    timezone: "America/New_York",
    closeHour: 16,
    closeMinute: 0,
  },
  {
    id: "dow",
    name: "Dow Jones",
    symbol: "^DJI",
    region: "USA",
    timezone: "America/New_York",
    closeHour: 16,
    closeMinute: 0,
  },
  {
    id: "eurostoxx50",
    name: "Euro Stoxx 50",
    symbol: "^STOXX50E",
    region: "EUROOPA",
    timezone: "Europe/Berlin",
    closeHour: 18,
    closeMinute: 0,
  },
  {
    id: "dax",
    name: "DAX",
    symbol: "^GDAXI",
    region: "SAKSAMAA",
    timezone: "Europe/Berlin",
    closeHour: 18,
    closeMinute: 0,
  },
  {
    id: "nikkei225",
    name: "Nikkei 225",
    symbol: "^N225",
    region: "JAAPAN",
    timezone: "Asia/Tokyo",
    closeHour: 15,
    closeMinute: 30,
  },
  {
    id: "omxtallinn",
    name: "OMX Tallinn",
    symbol: "^OMXTGI",
    region: "EESTI",
    timezone: "Europe/Tallinn",
    closeHour: 16,
    closeMinute: 15,
  },
];
